apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 30
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: alexmt/argocd-demo:f27903964ba8e31ad89c31379e300a35fe1632a3
        name: demo
        ports:
        - containerPort: 8080
